feat: update to angular 19 and rework
  - remove angular material and angular ssr from base project configuration
  - convert eslint config to eslint 9
  - add mission to README.md and make further refinements
  - refine scripts in package.json
  - add github action pull request workflow

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,3 +1,11 @@
 #!/bin/bash
 
-npx --no -- commitlint --edit ${1}
+npx --no -- commitlint --edit ${1} || {
+  # Print if commit message fails
+  echo -e 'Example conventional-commit messages:'
+  echo -e '- "feat: add user service for authentication"'
+  echo -e '- "fix(auth): correct validation error in login form"'
+  echo -e '- "chore(ci): update CI configuration to use Node 22"'
+  echo -e ''
+  exit 1
+}
